Description: CD12352 - Infrastructure as Code Project - S3 Bucket without ACLs

Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket to store static content.

Resources:
  StaticContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  StaticContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticContentBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"

Outputs:
  S3BucketURL:
    Value: !GetAtt [StaticContentBucket, WebsiteURL]
    Description: URL of the S3 bucket
